### ISSUE TITLE
Sanity check doesn't deny absolute paths

### ISSUE THREAD

**Issue by notpushkin** [reo7sp/http-repo#1]
Example:

```
$ curl http://127.0.0.1:8080//etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
...
```
(Note the double `/` in the URL)

Probably would be nice to take account of some other edge cases – [`werkzeug.utils.secure_filename`][wz] might be a good starting point. I can try to work out a PR tonight :)

[wz]: https://github.com/pallets/werkzeug/blob/d129d17066768238139b8f8a5d667d9a4f4d68db/werkzeug/utils.py#L253

**Comment by reo7sp** [comment]
Thanks!

**Comment by notpushkin** [comment]
<sup>Ну блин, а я только уж подумал, что первый PR для хактоберфеста готов ;')</sup>
